package com.fubang.live.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROOM_LIST_ENTITY".
 */
public class RoomListEntity {

    private Long id;
    private String roomid;
    private String roomname;
    private String roompic;
    private String roomrs;
    private String roompwd;
    private String rscount;
    private String gateway;
    /**
     * nuserid : 103921876
     * cphoto : 20170424043324_43.jpg
     * bphoto : 20170424043324_989.jpg
     * calias : 曹佳琪
     * cidiograph : 是回家简陋哈哈哈
     * guanzhunum : 0
     * state : 1
     * ngender : 0
     */

    private String nuserid;
    private String cphoto;
    private String bphoto;
    private String calias;
    private String cidiograph;
    private String guanzhunum;
    private String state;
    private String ngender;

    public RoomListEntity() {
    }

    public RoomListEntity(Long id) {
        this.id = id;
    }

    public RoomListEntity(Long id, String roomid, String roomname, String roompic, String roomrs, String roompwd, String rscount, String gateway) {
        this.id = id;
        this.roomid = roomid;
        this.roomname = roomname;
        this.roompic = roompic;
        this.roomrs = roomrs;
        this.roompwd = roompwd;
        this.rscount = rscount;
        this.gateway = gateway;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoomid() {
        return roomid;
    }

    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    public String getRoomname() {
        return roomname;
    }

    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }

    public String getRoompic() {
        return roompic;
    }

    public void setRoompic(String roompic) {
        this.roompic = roompic;
    }

    public String getRoomrs() {
        return roomrs;
    }

    public void setRoomrs(String roomrs) {
        this.roomrs = roomrs;
    }

    public String getRoompwd() {
        return roompwd;
    }

    public void setRoompwd(String roompwd) {
        this.roompwd = roompwd;
    }

    public String getRscount() {
        return rscount;
    }

    public void setRscount(String rscount) {
        this.rscount = rscount;
    }

    public String getGateway() {
        return gateway;
    }

    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

    public String getNuserid() {
        return nuserid;
    }

    public void setNuserid(String nuserid) {
        this.nuserid = nuserid;
    }

    public String getCphoto() {
        return cphoto;
    }

    public void setCphoto(String cphoto) {
        this.cphoto = cphoto;
    }

    public String getBphoto() {
        return bphoto;
    }

    public void setBphoto(String bphoto) {
        this.bphoto = bphoto;
    }

    public String getCalias() {
        return calias;
    }

    public void setCalias(String calias) {
        this.calias = calias;
    }

    public String getCidiograph() {
        return cidiograph;
    }

    public void setCidiograph(String cidiograph) {
        this.cidiograph = cidiograph;
    }

    public String getGuanzhunum() {
        return guanzhunum;
    }

    public void setGuanzhunum(String guanzhunum) {
        this.guanzhunum = guanzhunum;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getNgender() {
        return ngender;
    }

    public void setNgender(String ngender) {
        this.ngender = ngender;
    }
}
